const colors = {
  bg: "#0a0f1e",
  navBg: "#0d1424",
  cardBg: "#0d1424",
  deepBg: "#0a0f1e",
  border: "#1e2d45",
  borderBlue: "#1e3a5f",
  textPrimary: "#f0f6ff",
  textSecondary: "#e2e8f0",
  textMuted: "#94a3b8",
  textDim: "#64748b",
  green: "#4ade80",
  greenDark: "#16a34a",
  greenText: "#0a2e14",
  blue: "#60a5fa",
  yellow: "#f59e0b",
  red: "#f87171",
  purple: "#a78bfa",
};

const styles = {
  app: {
    minHeight: "100vh",
    background: colors.bg,
    color: colors.textSecondary,
    fontFamily: "'Segoe UI', sans-serif",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: 24,
    padding: "14px 32px",
    background: colors.navBg,
    borderBottom: `1px solid ${colors.border}`,
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  navBrand: { display: "flex", alignItems: "center", gap: 10, marginRight: "auto" },
  navLogo: { fontSize: 26 },
  navTitle: { fontSize: 20, fontWeight: 700, color: colors.green },
  navLinks: { display: "flex", gap: 4 },
  navLink: {
    color: colors.textMuted,
    textDecoration: "none",
    padding: "8px 16px",
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
  },
  navLinkActive: {
    background: "#1a2640",
    color: colors.green,
  },
  navUserBox: {
    padding: "8px 16px",
    background: "#0d1f36",
    borderRadius: 8,
    border: `1px solid ${colors.borderBlue}`,
    fontSize: 13,
    color: colors.textMuted,
  },
  navUserName: { color: colors.green, fontWeight: 700 },
  page: { padding: "32px 40px", maxWidth: 1200, margin: "0 auto" },
  pageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 32,
    flexWrap: "wrap",
    gap: 20,
  },
  pageTitle: { fontSize: 28, fontWeight: 800, color: colors.textPrimary, margin: "0 0 4px" },
  pageSubtitle: { color: colors.textDim, fontSize: 14, margin: 0 },
  loader: { textAlign: "center", padding: 80, color: colors.textDim, fontSize: 16 },
  loginBg: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "radial-gradient(ellipse at 50% 0%, #0d2045 0%, #0a0f1e 70%)",
  },
  loginCard: {
    background: colors.cardBg,
    border: `1px solid ${colors.border}`,
    borderRadius: 20,
    padding: "48px 40px",
    width: "100%",
    maxWidth: 420,
    boxShadow: "0 25px 80px rgba(0,0,0,0.5)",
  },
  loginIcon: { fontSize: 42, textAlign: "center", marginBottom: 8 },
  loginTitle: { textAlign: "center", fontSize: 28, fontWeight: 800, color: colors.textPrimary, margin: "0 0 4px" },
  loginSubtitle: { textAlign: "center", color: colors.textDim, fontSize: 14, marginBottom: 32 },
  errorBanner: {
    background: "#3b1414",
    border: "1px solid #7f1d1d",
    borderRadius: 8,
    padding: "12px 16px",
    color: colors.red,
    fontSize: 13,
    marginBottom: 20,
  },
  formField: { marginBottom: 20 },
  formLabel: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  formInput: {
    width: "100%",
    background: "#141e33",
    border: `1px solid ${colors.border}`,
    borderRadius: 10,
    padding: "12px 16px",
    color: colors.textPrimary,
    fontSize: 15,
    outline: "none",
    boxSizing: "border-box",
  },
  formInputError: { borderColor: "#7f1d1d" },
  formErrMsg: { color: colors.red, fontSize: 12, marginTop: 6, display: "block" },
  loginBtn: {
    width: "100%",
    background: `linear-gradient(135deg, ${colors.greenDark}, ${colors.green})`,
    border: "none",
    borderRadius: 10,
    padding: "14px",
    color: colors.greenText,
    fontWeight: 700,
    fontSize: 16,
    cursor: "pointer",
    marginTop: 8,
  },
  loginHint: { textAlign: "center", fontSize: 12, color: "#475569", marginTop: 20 },
  inlineCode: { background: "#1e2d45", padding: "2px 6px", borderRadius: 4, color: colors.green, fontSize: 12 },
  statsRow: { display: "flex", gap: 12 },
  statCard: {
    background: colors.cardBg,
    border: "2px solid",
    borderRadius: 12,
    padding: "12px 20px",
    textAlign: "center",
    minWidth: 80,
  },
  statValue: { display: "block", fontSize: 24, fontWeight: 800 },
  statLabel: { display: "block", fontSize: 11, color: colors.textDim, textTransform: "uppercase" },
  tableWrap: {
    background: colors.cardBg,
    border: `1px solid ${colors.border}`,
    borderRadius: 16,
    overflow: "hidden",
  },
  table: { width: "100%", borderCollapse: "collapse" },
  tableHead: {
    background: colors.deepBg,
    padding: "14px 20px",
    textAlign: "left",
    fontSize: 11,
    fontWeight: 700,
    color: colors.textDim,
    textTransform: "uppercase",
    letterSpacing: 1,
    borderBottom: `1px solid ${colors.border}`,
  },
  tableRow: { borderBottom: "1px solid #111827" },
  tableCell: { padding: "16px 20px", fontSize: 14, color: "#cbd5e1", verticalAlign: "middle" },
  idBadge: { background: "#1e2d45", borderRadius: 6, padding: "4px 10px", fontSize: 13, color: colors.blue, fontWeight: 700 },
  patientCell: { display: "flex", alignItems: "center", gap: 12 },
  patientName: { fontWeight: 600, color: colors.textPrimary },
  emailText: { color: colors.blue },
  statusBadge: { display: "inline-block", padding: "4px 12px", borderRadius: 20, fontSize: 12, fontWeight: 600 },
  viewBtn: {
    background: "transparent",
    border: `1px solid ${colors.borderBlue}`,
    color: colors.green,
    borderRadius: 8,
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
  },
  avatarSm: {
    width: 36, height: 36, borderRadius: "50%",
    display: "flex", alignItems: "center", justifyContent: "center",
    fontWeight: 800, fontSize: 16, color: "#0a0f1e", flexShrink: 0,
  },
  avatarMd: {
    width: 48, height: 48, borderRadius: "50%",
    display: "flex", alignItems: "center", justifyContent: "center",
    fontWeight: 800, fontSize: 20, color: "#0a0f1e", flexShrink: 0,
  },
  avatarLg: {
    width: 80, height: 80, borderRadius: "50%",
    display: "flex", alignItems: "center", justifyContent: "center",
    fontWeight: 900, fontSize: 32, color: "#0a0f1e", flexShrink: 0,
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: 16,
  },
  patientCard: {
    background: colors.cardBg,
    border: `1px solid ${colors.border}`,
    borderRadius: 16,
    padding: "20px 24px",
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  cardInfo: { flex: 1, minWidth: 0 },
  cardName: { margin: "0 0 4px", fontSize: 16, fontWeight: 700, color: colors.textPrimary },
  cardEmail: { margin: "0 0 2px", fontSize: 13, color: colors.blue },
  cardPhone: { margin: 0, fontSize: 12, color: colors.textDim },
  cardViewBtn: {
    background: "transparent",
    border: `1px solid ${colors.borderBlue}`,
    color: colors.green,
    borderRadius: 8,
    padding: "8px 14px",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    flexShrink: 0,
  },
  searchInput: {
    background: colors.cardBg,
    border: `1px solid ${colors.border}`,
    borderRadius: 10,
    padding: "12px 20px",
    color: colors.textPrimary,
    fontSize: 14,
    outline: "none",
    minWidth: 280,
  },
  backBtn: {
    background: "transparent",
    border: `1px solid ${colors.borderBlue}`,
    color: colors.blue,
    borderRadius: 8,
    padding: "10px 20px",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    marginBottom: 24,
  },
  detailCard: { background: colors.cardBg, border: `1px solid ${colors.border}`, borderRadius: 20, padding: 40 },
  detailCardHeader: {
    display: "flex", alignItems: "center", gap: 24,
    marginBottom: 40, paddingBottom: 32,
    borderBottom: `1px solid ${colors.border}`,
  },
  detailName: { fontSize: 28, fontWeight: 800, color: colors.textPrimary, margin: "0 0 4px" },
  detailUsername: { color: colors.textDim, margin: "0 0 12px" },
  detailIdBadge: { background: "#1e3a5f", borderRadius: 8, padding: "6px 14px", fontSize: 13, color: colors.blue, fontWeight: 600 },
  detailGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 20 },
  detailItem: { display: "flex", gap: 16, alignItems: "flex-start", background: colors.deepBg, borderRadius: 12, padding: 20 },
  detailItemIcon: { fontSize: 22, flexShrink: 0 },
  detailItemLabel: { fontSize: 11, color: colors.textDim, textTransform: "uppercase", letterSpacing: 1, margin: "0 0 4px", fontWeight: 700 },
  detailItemValue: { fontSize: 14, color: colors.textSecondary, margin: 0 },
  perfGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 16, marginBottom: 32 },
  perfCard: { background: colors.cardBg, border: `1px solid ${colors.border}`, borderRadius: 16, padding: 24 },
  perfCardTitle: { margin: "0 0 12px", fontSize: 16, fontWeight: 700 },
  perfCardDesc: { fontSize: 13, color: colors.textMuted, lineHeight: 1.7, margin: "12px 0 0" },
  codeBlock: {
    background: colors.deepBg,
    borderRadius: 8,
    padding: "14px 16px",
    fontSize: 12,
    color: colors.green,
    overflowX: "auto",
    margin: 0,
    lineHeight: 1.6,
    fontFamily: "monospace",
  },
  triggerBtn: {
    marginTop: 16,
    background: "#1e2d45",
    border: `1px solid ${colors.borderBlue}`,
    color: colors.yellow,
    borderRadius: 8,
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
  },
  consoleBox: { background: "#050810", border: `1px solid ${colors.border}`, borderRadius: 16, overflow: "hidden", marginBottom: 24 },
  consoleHeader: {
    display: "flex", justifyContent: "space-between", alignItems: "center",
    padding: "12px 20px", background: colors.deepBg,
    borderBottom: `1px solid ${colors.border}`,
    fontSize: 14, fontWeight: 600, color: colors.textDim,
  },
  consoleClearBtn: { background: "#1e2d45", border: "none", color: colors.textMuted, borderRadius: 6, padding: "4px 12px", cursor: "pointer", fontSize: 12 },
  consoleLogs: {
    padding: "16px 20px",
    fontFamily: "monospace",
    fontSize: 13,
    maxHeight: 200,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  consoleLogLine: { display: "flex", gap: 12, lineHeight: 1.5 },
  consoleLogTime: { color: "#475569", flexShrink: 0 },
  apiPreviewBox: { background: colors.cardBg, border: `1px solid ${colors.border}`, borderRadius: 16, padding: 24, marginBottom: 24 },
  apiPreviewTitle: { margin: "0 0 16px", fontSize: 16, fontWeight: 700, color: colors.textPrimary },
  apiPreviewItem: { padding: "10px 0", borderBottom: "1px solid #111827", fontSize: 14, color: "#cbd5e1" },
  qaSection: { background: colors.cardBg, border: `1px solid ${colors.border}`, borderRadius: 16, padding: 32 },
  qaTitle: { margin: "0 0 24px", fontSize: 20, fontWeight: 700, color: colors.textPrimary },
  qaCard: { marginBottom: 20, padding: 20, background: colors.deepBg, borderRadius: 12, borderLeft: `3px solid ${colors.green}` },
  qaQuestion: { fontSize: 15, fontWeight: 700, color: colors.green, margin: "0 0 10px" },
  qaAnswer: { fontSize: 14, color: colors.textMuted, lineHeight: 1.7, margin: 0 },
};

export default styles;